name: unitenv
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.2.2
  - pytorch=
  - torchvision=
  - cudatoolkit=



  - numpy=1.23.3
  - numba==0.56.4
  - scipy==1.9.1
  - py-opencv=4.6.0
  - ipykernel=6.16
  - matplotlib=3.6.1
  - zarr=2.12.0
  - numcodecs=0.10.2
  - h5py=3.7.0
  - hydra-core=1.2.0
  - einops=0.4.1
  - tqdm=4.64.1
  - scikit-image=0.19.3
  - wandb=0.13.3
  - threadpoolctl=3.1.0
  - imageio=2.22.0
  - imageio-ffmpeg=0.4.7
  - tensorboard=2.10.1
  - datasets=2.6.1
  - diffusers=0.11.1
  - timm=0.9.7

  - pytorch3d=0.7.0
  - av=10.0.0 ###xxxx  
  - psutil=5.9.2 ####
  - gym=0.21.0 ####xxx
  - pymunk=6.2.1 ####xxx
  - scikit-video=1.1.11
  - accelerate=0.13.2
  - cffi=1.15.1
  - cython=0.29.32  
  - cmake=3.24.3  
  - llvm-openmp=14 
  - tensorboardx=2.5.1
  - termcolor=2.0.1  
  - dill=0.3.5.1  
  - shapely=1.8.4
  - click=8.0.4
  - boto3=1.24.96
  - imagecodecs==2022.8.8

  - pip:
    - ray[default,tune]==2.2.0 ####xxx
    - free-mujoco-py==2.1.6 ####
    - pygame==2.1.2 ####
    - robosuite @ https://github.com/cheng-chi/robosuite/archive/277ab9588ad7a4f4b55cf75508b44aa67ec171f0.tar.gz ###xxx
    - robomimic==0.2.0 ###xxx
    - pytorchvideo==0.1.5 ###xxx
    - imagecodecs==2022.9.26 ###xxx
    - r3m @ https://github.com/facebookresearch/r3m/archive/b2334e726887fa0206962d7984c69c5fb09cceab.tar.gz
    - dm-control==1.0.9 ####xxx

    - byol-pytorch
    - pytorch-lightning==2.5.1
    - rerun-sdk==0.15.1
