name: train_mae_perception
_target_: UniT.workspace.train_mae_perception_workspace.TrainMaePerceptionWorkspace
dataset_path: &dataset_path data/3D_pose_gelsight
horizon: &horizon 1

task:
  dataset:
    _target_: UniT.dataset.tactile_perception_dataset.TactilePerceptionDataset
    resized_image_shape: [224,224]
    shape_meta:   
      obs:    
        tactile_image:
          shape: [3, 240, 320]
          type: rgb
        3Dpose:
          shape: [4]
          type: low_dim
    dataset_path: *dataset_path
    horizon: *horizon
    seed: 42
    val_ratio: 0.1
    max_train_episodes: null

device: &device cuda:0
model:
  _target_: UniT.perception.byol_perception.ByolPerception
  byol_config:
    pt_path: representation_models/byol-key-resnet50-pretrain.pt
    device: *device
  freeze_encoder: True

dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: true
  pin_memory: false
  persistent_workers: False

val_dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: False
  pin_memory: false
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: *device
  seed: 42
  resume: True
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 3000
  gradient_accumulate_every: 1
  checkpoint_every: 1
  val_every: 10
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0


logging:
  project: 3Dpose_benchmark
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}
  tags: ["${name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: train_loss
    mode: min
    k: 5
    format_str: 'epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
    subdir: ${hydra.job.num}